clc;
clear;
close all;
tm=100
k=1
%====================================
syms s
den=s*(s+1)*(0.5*s+1);
den=collect(den,s);
den=sym2poly(den);
%====================================
h=2;l=2;n=1;
%====================================
kp=0;
out=sim('Nonlinearity');
hf=figure(1);
subplot(h,l,n);n=n+1;
plot(out.e,out.de);
myPlotFormat([],[],hf,'误差端的相轨迹,kp=0',1);
subplot(h,l,n);n=n+1;
plot(out.c,out.dc);
myPlotFormat([],[],hf,'输出端的相轨迹,kp=0',1);
subplot(h,l,n);n=n+1;
plot(out.tout,out.e);
myPlotFormat([],[],hf,'误差,kp=0',1);
subplot(h,l,n);n=n+1;
plot(out.tout,out.c);
myPlotFormat([],[],hf,'输出,kp=0',1);
%====================================
h=2;l=2;n=1;
%====================================
kp=0.1;
out=sim('Nonlinearity');
hf=figure(2);
subplot(h,l,n);n=n+1;
plot(out.e,out.de);
myPlotFormat([],[],hf,'误差端的相轨迹,kp=0.1',1);
subplot(h,l,n);n=n+1;
plot(out.c,out.dc);
myPlotFormat([],[],hf,'输出端的相轨迹,kp=0.1',1);
subplot(h,l,n);n=n+1;
plot(out.tout,out.e);
myPlotFormat([],[],hf,'误差,kp=0.1',1);
subplot(h,l,n);n=n+1;
plot(out.tout,out.c);
myPlotFormat([],[],hf,'输出,kp=0.1',1);
%====================================
Gs=tf(k,den);
[re,im,w]=nyquist(Gs);
re=squeeze(re);
im=squeeze(im);
hf=figure(3);
plot(re,im);
myPlotFormat([],[],hf,'奈奎斯特曲线',1);
%====================================
syms w
num1=k;
den1=den;
den1=poly2sym(den1,s);
Gs1=num1/den1;
Gw=subs(Gs1,s,1j*w);
reGw=real(Gw);
imGw=imag(Gw);
sow=solve(imGw==0,w)